package com.bike.order.domain;

public enum BikeOrderStatusEnum {
    NEW,PENDING_VALIDATION, VALIDATED,VALIDATION_EXCEPTION,PENDING_ALLOCATION, ALLOCATED, ALLOCATION_EXCEPTION, PENDING_INVENTORY, PICKED_UP, DELIVERED, DELIVERY_EXCEPTION, CANCELED
}
